version: "1.0"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/kvarzsiev/.config/homepage/config:/app/config # Make sure your local config directory exists
      - /home/kvarzsiev/.config/homepage/images:/app/public/images # for background image conf
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/kvarzsiev/.config/qbittorrent/config:/config
      - /home/kvarzsiev/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/kvarzsiev/.config/radarr/config:/config
      - /home/kvarzsiev/movies #optional
      - /home/kvarzsiev/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
