version: "1.0"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/kvarzsiev/.config/homepage/config:/app/config # Make sure your local config directory exists
      - /home/kvarzsiev/.config/homepage/images:/app/public/images # for background image conf
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
